# Add donor provenance by exact deterministic replay; do not mutate frozen H5ADs.
from pathlib import Path
script=Path(__file__).with_name('deploy_diagnostics.py');prefix=script.read_text().split("for name,stage in [('mab','E9.5'),('gata4','E8.75')]:")[0];exec(compile(prefix,str(script),'exec'),globals())
report=[]
for name,stage in [('mab','E9.5'),('gata4','E8.75')]:
 response=model.predict('Mab21l2' if name=='mab' else 'Gata4',method);a=ad.read_h5ad('/workspace/shared/virtual_embryo_data/'+stage+'.h5ad');X=a.X.toarray() if hasattr(a.X,'toarray') else np.asarray(a.X);ix=np.sort(np.random.default_rng(20260904).choice(len(X),7449,replace=False));base=X[ix];obs=a.obs.iloc[ix];state=model.assign(base);zz=model.pca.transform(base);dd=np.linalg.norm(zz-model.km.cluster_centers_[state],axis=1);outside=dd>threshold[state];supported=response['support'][state];lineage=obs.celltype.astype(str).isin(['V-CM','IFT-CM','HEM-Endoth','Intra-Endoth-1','Intra-Endoth-2']).to_numpy()|obs.cm_celltype.astype(str).isin(['vCM1','vCM2','aCM1','aCM2','OFT/RV-CM','aSHF','pSHF']).to_numpy()
 for variant,mask in [('all_supported',supported)]+([('positive_lineage',supported&lineage)] if name=='gata4' else []):
  y,di=model.emit(base[mask],response,mode=mode);f=O/f'{name}_{variant}.h5ad';saved=ad.read_h5ad(f).X;assert np.array_equal(saved[mask],y),'Replay mismatch';donor=np.arange(len(base));donor[mask]=np.flatnonzero(mask)[di];original=base[donor]
  pd.DataFrame(dict(recipient_row=np.arange(len(base)),recipient_obs_id=obs.index.astype(str),donor_carrier_row=donor,donor_original_row=ix[donor],donor_obs_id=obs.index.astype(str).to_numpy()[donor],recipient_state=state,donor_state=state[donor],recipient_outside95=outside,donor_outside95=outside[donor],in_gate=mask)).to_csv(O/f'{name}_{variant}_DONOR_PROVENANCE.csv',index=False)
  report.append(dict(stage=name,variant=variant,exact_emitter_replay='PASS',rowwise_recipient_zero_to_positive=int(((base==0)&(saved>0)).sum()),donor_relative_zero_to_positive=int(((original==0)&(saved>0)).sum()),donor_relative_positive_to_zero=int(((original>0)&(saved==0)).sum()),donor_outside95_fraction=float(outside[donor].mean()),recipient_outside95_fraction=float(outside.mean()),source_state_counts_before=np.bincount(state,minlength=8).tolist(),source_state_counts_after_sampling=np.bincount(state[donor],minlength=8).tolist(),note='Source state is sampled WT donor identity, not target-trained celltype or inferred post-perturbation fate; coordinates kept at recipient slots'))
(O/'REPLAY_PROVENANCE.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
